Exception on /pubEndpoint_receiveGenericFriendRequest [POST]
Traceback (most recent call last):
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/publicEndpoints.py", line 91, in pubEndpoint_receiveGenericFriendRequest
    return json.dumps(friends_receiveGetIpRequest(request_object_json))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/friends.py", line 94, in friends_receiveGetIpRequest
    ownLocalIP = friends_getLocalIP()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/friends.py", line 218, in friends_getLocalIP
    hostname = socket.gethostname()
               ^^^^^^
NameError: name 'socket' is not defined. Did you forget to import 'socket'
