Exception on /privEndpoint_sendMessage [POST]
Traceback (most recent call last):
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/privateEndpoints.py", line 60, in privEndpoint_sendMessage
    print("p2p_getFriendConnectionStatus() = ", p2p_getFriendConnectionStatus())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/p2p.py", line 531, in p2p_getFriendConnectionStatus
    if friendConnectionStatus == 0:
       ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'friendConnectionStatus' is not defined. Did you mean: 'p2p_getFriendConnectionStatus'?
Exception on /privEndpoint_sendMessage [POST]
Traceback (most recent call last):
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/privateEndpoints.py", line 60, in privEndpoint_sendMessage
    print("p2p_getFriendConnectionStatus() = ", p2p_getFriendConnectionStatus())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/p2p.py", line 531, in p2p_getFriendConnectionStatus
    if friendConnectionStatus == 0:
       ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'friendConnectionStatus' is not defined. Did you mean: 'p2p_getFriendConnectionStatus'?
Exception on /privEndpoint_sendMessage [POST]
Traceback (most recent call last):
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/privateEndpoints.py", line 60, in privEndpoint_sendMessage
    print("p2p_getFriendConnectionStatus() = ", p2p_getFriendConnectionStatus())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renner/special/mac0499-prototype/src/server/p2p.py", line 531, in p2p_getFriendConnectionStatus
    if friendConnectionStatus == 0:
       ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'friendConnectionStatus' is not defined. Did you mean: 'p2p_getFriendConnectionStatus'?
